apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haleem00/argocd-app-deploy.git  # Change to your Git repo
    targetRevision: HEAD  # Change branch/tag if needed
    path: Kubernetes  # Change to the correct directory in your repo
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app  # Change to your desired namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
