apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: LoadBalancer   # Change from NodePort to LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30007  # No need for nodePort when using LoadBalancer
  selector:
    app: netflix-app
